### ISSUE TITLE
CFBundleIdentifier doesn't exist  and rubicon-icon-font.ttf neither ????

### ISSUE THREAD

**Issue by vmacavero** [hasura/react-native-auth-boilerplate#9]
Hi, react-native run-ios produces this error.

I'm in VANILLA branch(no expo for me, i prefer a simple and clean life :) ) .

react-native-cli: 1.2.0
react-native: 0.54.4

Using Xcode, i have a different error : 

[...]react-native-auth-boilerplate/vanilla/node_modules/native-base/Fonts/rubicon-icon-font.ttf: No such file or directory

Also :
Is it correct that this project is missing facebook Auth for the Vanilla branch ?

Thanks.

Victor

**Comment by wawhal** [comment]
Hey @vmacavero 

1. `CFBundleIdentifier doesn't exist` happens generally because some parts of your react-native cache is corrupt.  Please run

```
$ rm -rf ~/.rncache
$ rm -rf node_modules
$ npm install
```
[This PR](https://github.com/hasura/react-native-auth-boilerplate/pull/10) fixes it.

2. The `rubicon-icon-font.ttf` bug is my fault. In the last PR, package-lock.json was not committed. So the versions of the peer dependencies were not maintained, which broke the xcode project. I should have been careful while merging.

3. Yes Facebook login is not yet done. It is a WIP.

Thanks a lot for reporting.

**Comment by vmacavero** [comment]
Thanks @wawhal  ! I'll check soon for the CFBundleidentifier problem (that was a super-fresh install, so it's a bit strange) to be fixed and report back.


Victor

**Comment by hpelitebook745G2** [comment]
@wawhal I did the three steps, yet I still get the error. What am i missing?
`react-native-cli: 2.0.1
react-native: 0.47.2

"native-base": "^2.3.1",`

These are my versions.

**Comment by wawhal** [comment]
Hey @hpelitebook745G2 

CFBundleIdentifier could happen due to a lot of reasons of which corrupt `.rncache` is a common one.  Go through these issues and hopefully you'll find a solution:

https://github.com/facebook/react-native/issues/14447
https://github.com/facebook/react-native/issues/14452
https://github.com/facebook/react-native/issues/14969

**Comment by nyousaf47** [comment]
@wawhal  i tried it , but does not work for me.

**Comment by wawhal** [comment]
@nyousaf47 It will be better if you elaborate. 
What does not work? What is the error? Versions?
